// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopeeApp.Data;

#nullable disable

namespace ShopeeApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopeeApp.Models.Category.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Телефони"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ноутбуки"
                        });
                });

            modelBuilder.Entity("ShopeeApp.Models.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Новий iPhone",
                            Name = "iPhone 17 Pro Max APPLE (6.9'' - 256 GB)",
                            Price = 14999.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Новий SAMSUNG",
                            Name = "Smartphone SAMSUNG Galaxy S25 FE (6.7'' - 8 GB - 512 GB)",
                            Price = 1082.10m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Потужний ноутбук",
                            Name = "Smartphone OPPO Reno 14 (6.59'' - 12 GB - 512 GB)",
                            Price = 649.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Потужний ноутбук",
                            Name = "Portátil HP Laptop 15-fd0019np (15.6\" - Intel Core i3 N305 - RAM:8 GB - 256 GB SSD - Intel UHD)",
                            Price = 549.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Потужний ноутбук",
                            Name = "Portátil HP OmniBook Ultra Flip 14-fh0005np (14'' - Intel Core Ultra 7 256V - RAM: 16 GB - 1 TB SSD - Intel Arc Graphics)",
                            Price = 1899.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Portátil ASUS Vivobook M1502YA (15.6\" - RYZEN 7 7730U - Ram: 16GB - 1TB)",
                            Name = "MacBook Pro",
                            Price = 749.99m
                        });
                });

            modelBuilder.Entity("ShopeeApp.Models.Product.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "iPhone17_1.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            FileName = "iPhone17_2.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            FileName = "iPhone17_3.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            FileName = "oppo_Reno14_1.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            FileName = "oppo_Reno14_2.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            FileName = "samsung_phone_1.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 7,
                            FileName = "samsung_phone_2.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 8,
                            FileName = "samsung_phone_3.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 9,
                            FileName = "asus_1.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 10,
                            FileName = "hp_1.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 11,
                            FileName = "hp_2.jpg",
                            ProductId = 6
                        });
                });

            modelBuilder.Entity("ShopeeApp.Models.Product.Product", b =>
                {
                    b.HasOne("ShopeeApp.Models.Category.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopeeApp.Models.Product.ProductImage", b =>
                {
                    b.HasOne("ShopeeApp.Models.Category.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("ShopeeApp.Models.Product.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopeeApp.Models.Category.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopeeApp.Models.Product.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
